# Build stage
FROM golang:1.22.2-bookworm AS builder

RUN apt install gcc g++ make ca-certificates
WORKDIR /app

COPY ./src/go.mod ./src/go.sum ./
RUN go mod download && go mod verify

COPY . .

WORKDIR /app/src
RUN CGO_ENABLED=0 go build -o ./binary ./cmd

# Run stage
FROM alpine
COPY ./config.json .
COPY ./src/templates ./templates
COPY --from=builder /app/src/binary ./
EXPOSE 8080
CMD ["./binary"]
