name: Publish Docker Image

on:
    push:
        branches:
            - production

jobs:
    push-to-registry:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  file: ./Dockerfile-prod
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/daily-dashboard:latest
